HOST_IP = "YOUR SERVER IP THAT IS EXPOSED TO THE INTERNET"
HTTPS = "https://%s" % HOST_IP
SECRET_KEY = 'AweseomelySecretKeyThatNobodyCanGuessJustTryandCrack!tComeon'
MAIL_USERNAME = 'YOUR GMAIL'
MAIL_PASSWORD = 'YOUR GMAIL PASSWORD'
COPILOT_URL = 'https://api.cai.tools.sap/auth/v1/owners/YOUR ACCOUNT'
COPILOT_AUTH = 'YOUR TOKEN'
COPILOT_DEV_TOKEN = 'Token YOUR TOKEN'
