"""
Central management for models.
TODO surface for UI configuration

"""
OSINTModel = {
            "Person": {
                "DateOfBirth": "datetime",
                "PlaceOfBirth": "string",
                "FirstName": "string",
                "LastName": "string",
                "MidName": "string",
                "description": "string",
                "icon": "string",
                "Gender": "string",
                "class": "V",
                "Ext_key": "string",
                "hashkey": "string"
            },
            "Object": {
                "class": "V",
                "Category": "string",
                "description": "string",
                "Tags": "string",
                "icon": "string",
                "title": "string",
                "Ext_key": "string",
                "hashkey": "string"

            },
            "Organization": {
                "class": "V",
                "Category": "string",
                "description": "string",
                "Tags": "string",
                "Members": "integer",
                "Founded": "datetime",
                "Name": "string",
                "OtherNames": "string",
                "UCDP_id": "string",
                "ACLED_id": "string",
                "Source": "string",
                "icon": "string",
                "title": "string",
                "Ext_key": "string",
                "hashkey": "string"
            },
            "Profile": {
                "class": "V",
                "Category": "string",
                "description": "string",
                "Tags": "string",
                "Friends": "integer",
                "Followers": "integer",
                "Name": "string",
                "OtherNames": "string",
                "Posts": "integer",
                "DateCreated": "datetime",
                "url": "string",
                "Source": "string",
                "Screen_name": "string",
                "icon": "string",
                "title": "string",
                "Ext_key": "string",
                "hashkey": "string"
            },
            "Post": {
                "class": "V",
                "Category": "string",
                "description": "string",
                "Tags": "string",
                "DateCreated": "datetime",
                "RePosts": "integer",
                "Likes": "integer",
                "Author": "string",
                "url": "string",
                "Source": "string",
                "icon": "string",
                "title": "string",
                "Ext_key": "string",
                "hashkey": "string"
            },
            "Tag": {
                "class": "V",
                "Category": "string",
                "description": "string",
                "Source": "string",
                "icon": "string",
                "title": "string",
                "Ext_key": "string",
                "hashkey": "string"
            },
            "Location": {
                "class": "V",
                "hash": "string",
                "Category": "string",
                "description": "string",
                "Tags": "string",
                "Latitude": "float",
                "Longitude": "float",
                "city": "string",
                "pop": "integer",
                "country": "string",
                "iso3": "string",
                "province": "string",
                "icon": "string",
                "title": "string",
                "Ext_key": "string",
                "hashkey": "string"
            },
            "Event": {
                "class": "V",
                "hash": "string",
                "Category": "string",
                "description": "string",
                "Tags": "string",
                "StartDate": "datetime",
                "EndDate": "datetime",
                "icon": "string",
                "title": "string",
                "Sources": "string",
                "Deaths": "string",
                "Civilians": "string",
                "Origin": "string",
                "UCDP_id": "string",
                "Source": "string",
                "Ext_key": "string",
                "hashkey": "string"
            },
            "Case": {
                "class": "V",
                "hash": "string",
                "Name": "string",
                "Owners": "string",
                "description": "string",
                "Classification": "string",
                "StartDate": "datetime",
                "LastUpdate": "datetime",
                "CreatedBy": "string",
                "Members": "string",
                "Ext_key": "string",
                "hashkey": "string"
            },
            "AttackPattern": {
                "class": "V",
                "created_by_ref": "string",
                "description": "string",
                "external_references": "string",
                "kill_chain_phases": "string",
                "labels": "string",
                "modified": "string",
                "name": "string",
                "source": "string",
                "type": "string",
                "Ext_key": "string",
                "hashkey": "string"
            },
            "Campaign": {
                "class": "V",
                "aliases": "string",
                "created_by_ref": "string",
                "description": "string",
                "first_seen": "datetime",
                "labels": "string",
                "last_seen": "datetime",
                "modified": "string",
                "name": "string",
                "objective": "string",
                "revoked": "string",
                "source": "string",
                "type": "string",
                "Ext_key": "string",
                "hashkey": "string"
            },
            "CourseOfAction": {
                "class": "V",
                "action": "string",
                "created_by_ref": "string",
                "description": "string",
                "labels": "string",
                "modified": "datetime",
                "name": "string",
                "revoked": "string",
                "source": "string",
                "type": "string",
                "Ext_key": "string",
                "hashkey": "string"
            },
            "Identity": {
                "class": "V",
                "contact_information": "string",
                "created_by_ref": "string",
                "description": "string",
                "identity_class": "string",
                "labels": "string",
                "modified": "string",
                "name": "string",
                "revoked": "string",
                "sectors": "string",
                "source": "string",
                "type": "string",
                "Ext_key": "string",
                "hashkey": "string"
            },
            "Indicator": {
                "class": "V",
                "created_by_ref": "string",
                "description": "string",
                "kill_chain_phases": "string",
                "labels": "string",
                "modified": "string",
                "name": "string",
                "pattern": "string",
                "revoked": "string",
                "source": "string",
                "type": "string",
                "valid_from": "datetime",
                "valid_until": "datetime",
                "Ext_key": "string",
                "hashkey": "string"
            },
            "IntrusionSet": {
                "class": "V",
                "aliases": "string",
                "created_by_ref": "string",
                "description": "string",
                "first_seen": "datetime",
                "goals": "string",
                "labels": "string",
                "last_seen": "datetime",
                "modified": "string",
                "name": "string",
                "primary_motivation": "string",
                "resource_level": "string",
                "revoked": "string",
                "secondary_motivations": "string",
                "source": "string",
                "type": "string",
                "Ext_key": "string",
                "hashkey": "string"
            },
            "Malware": {
                "class": "V",
                "created_by_ref": "string",
                "description": "string",
                "kill_chain_phases": "string",
                "labels": "string",
                "modified": "string",
                "name": "string",
                "revoked": "string",
                "source": "string",
                "type": "string",
                "Ext_key": "string",
                "hashkey": "string"
            },
            "ObservedData": {
                "class": "V",
                "created_by_ref": "string",
                "description": "string",
                "first_observed": "datetime",
                "labels": "string",
                "last_observed": "datetime",
                "modified": "string",
                "number_observed": "string",
                "objects": "string",
                "revoked": "string",
                "source": "string",
                "type": "string",
                "Ext_key": "string",
                "hashkey": "string"
            },
            "Report": {
                "class": "V",
                "created_by_ref": "string",
                "description": "string",
                "labels": "string",
                "modified": "string",
                "name": "string",
                "object_refs": "string",
                "published": "datetime",
                "revoked": "string",
                "source": "string",
                "type": "string",
                "Ext_key": "string",
                "hashkey": "string"
            },
            "Sighting": {
                "class": "V",
                "count": "string",
                "created_by_ref": "string",
                "description": "string",
                "first_seen": "datetime",
                "labels": "string",
                "last_seen": "datetime",
                "modified": "string",
                "observed_data_refs": "string",
                "revoked": "string",
                "sighting_of_ref": "string",
                "source": "string",
                "summary": "string",
                "type": "string",
                "where_sighted_refs": "string",
                "Ext_key": "string",
                "hashkey": "string"
            },
            "ThreatActor": {
                "class": "V",
                "aliases": "string",
                "created_by_ref": "string",
                "description": "string",
                "goals": "string",
                "labels": "string",
                "modified": "string",
                "name": "string",
                "personal_motivations": "string",
                "primary_motivation": "string",
                "resource_level": "string",
                "revoked": "string",
                "roles": "string",
                "secondary_motivations": "string",
                "sophistication": "string",
                "source": "string",
                "type": "string",
                "Ext_key": "string",
                "hashkey": "string"
            },
            "Tool": {
                "class": "V",
                "created_by_ref": "string",
                "description": "string",
                "kill_chain_phases": "string",
                "labels": "string",
                "modified": "string",
                "name": "string",
                "revoked": "string",
                "source": "string",
                "tool_version": "string",
                "type": "string",
                "Ext_key": "string",
                "hashkey": "string"
            },
            "Vulnerability": {
                "class": "V",
                "created_by_ref": "string",
                "description": "string",
                "labels": "string",
                "modified": "string",
                "name": "string",
                "revoked": "string",
                "source": "string",
                "type": "string",
                "Ext_key": "string",
                "hashkey": "string"
            },
            "Process": {
                "class": "V",
                "category": "string",
                "name": "string",
                "started": "datetime",
                "description": "string",
                "pid": "string",
                "ended": "datetime",
                "summary": "string",
                "hashkey": "string"
            },
            "Monitor": {
                "user": "string",
                "name": "string",
                "type": "string",
                "searchValue": "string",
                "description": "string",
                "icon": "string",
                "class": "V",
                "hashkey": "string"
            },
            "User": {
                "userName": "string",
                "hashkey": "string",
                "description": "string",
                "class": "V"
            }
        }

UserModel = {
            "User": {
                "createDate": "datetime",
                "userName": "string",
                "passWord": "string",
                "email": "string",
                "icon": "string",
                "confirmed": "boolean",
                "class": "V",
                "hashkey": "string"
            },
            "Message": {
                "class": "V",
                "text": "string",
                "title": "string",
                "tags": "string",
                "sender": "string",
                "receiver": "string",
                "icon": "string",
                "createDate": "datetime",
                "hashkey": "string"
            },
            "Session": {
                "user": "string",
                "startDate": "datetime",
                "endDate": "datetime",
                "ipAddress": "string",
                "token": "string",
                "icon": "string",
                "class": "V",
                "hashkey": "string"
            },
            "Blacklist": {
                "token": "string",
                "user": "string",
                "session": "string",
                "createDate": "string",
                "icon": "string",
                "class": "V",
                "hashkey": "string"
            }
        }

POLEModel = {
            "Person": {
                "key": "integer",
                "DateOfBirth": "datetime",
                "PlaceOfBirth": "string",
                "FirstName": "string",
                "LastName": "string",
                "MidName": "string",
                "icon": "string",
                "Gender": "string",
                "class": "V",
                "hashkey": "string"
            },
            "Object": {
                "key": "integer",
                "class": "V",
                "Category": "string",
                "description": "string",
                "Tags": "string",
                "hashkey": "string"
            },
            "Location": {
                "key": "integer",
                "class": "V",
                "Category": "string",
                "description": "string",
                "Tags": "string",
                "Latitude": "float",
                "Longitude": "float",
                "city": "string",
                "pop": "integer",
                "country": "string",
                "iso3": "string",
                "province": "string",
                "hashkey": "string"
            },
            "Event": {
                "class": "V",
                "Category": "string",
                "description": "string",
                "Tags": "string",
                "StartDate": "datetime",
                "EndDate": "datetime",
                "hashkey": "string"
            },
            "BaseNames": {
                "class": "V",
                "Name": "string",
                "NameType" : "string",
                "NameOrigin": "string",
                "hashkey": "string"
            },
            "Case": {
                "class": "V",
                "Name": "string",
                "Owners": "string",
                "Classification": "string",
                "StartDate": "datetime",
                "LastUpdate": "datetime",
                "CreatedBy": "string",
                "Members": "string",
                "hashkey": "string",
                "description": "string"
            }
        }
